### ISSUE TITLE
Role assignment lost on respawn

### ISSUE THREAD

**Issue by Spoffy** [Savage-Game-Design/Mike-Force#22]
> When you respawn, any role assignment (medic/engineer/explosives/RTO) is lost. 

(Note: This is not a good example of a bug report, but this is all the information available at this time)

**Comment by Alablm** [comment]
@Spoffy This doesn't seem to effect anything for the most part, just hides names from the 'H' menu - the only time that I've been able to confirm players actually losing their role is when they try to reassign the same role after dying, and they fall off of the missionNamespace variable (`vn_mf_traits_arr`) after their first death because player names change for some reason.

**Comment by Alablm** [comment]
Fixed in the current release, closing.
