### ISSUE TITLE
Bad Performance/Desync

### ISSUE THREAD

**Issue by wildsevenmoony** [Savage-Game-Design/Mike-Force#25]
Hello, 

I started this report on the Workshop Page with these comments: 

"Anybody has desync issues? Like, my server never desyncs with multiple people and mods. Now with this, a few mods and only 2 people I see alot of desync"

"Even without mods we have a massive desync problem"

and received SGDs reply: 
"Server is probably not quite up to running Mike Force. We've noticed some issues in the CDLC/MF using a lot of server memory, which spoils server performance and causes desync.

We're investigating currently. In the meantime, I'd recommend using a server with 6GB or more of RAM, and restarts every few hours!"

and now I figured I move here.

The issue is I don't think our server is the issue here. We rent a server hosted at hetzner and never had desync issues. Here are our specs: 
Microsoft Windows Server 2012 R2 Standard
Intel(R) Xeon(R) CPU E3-1271 v3 @ 3.60GHz, 3601 Mhz, 4 Core(s), 8 Logical Processor(s)
32.0 GB of RAM

In our usual missions on this server we have 49 FPS (Server) and no desync what so ever. Its only this mission. I even added a HC which did nothing. 

I don't know if the RPT-File helps at all but you can see it here (a game without mods): https://pastebin.com/pxQMSGgQ

What I find odd is that I can't find any one else with a desync issue online and I have no idea why it happens for us. 

If you need further information please tell me.

Many Greetings
Moony

**Comment by JDownward** [comment]
the desync is high on my server also (using armahosts)

**Comment by Spoffy** [comment]
Hi @stafmoony - the issue is with both your server setup and the CDLC. Thanks for providing the .rpt, it made this really easy to spot.

The CDLC (and especially Mike Force) has been experience issues with runaway memory - we've seen it climb really high on our servers - as high as 18GB at one point.

We're actively investigating the issue, but in the meantime, we recommend running with at least 6GB of memory (ideally 8GB) and restarting at least every 6 hours.

In terms of your server setup - you've got Arma 3 limited to 4GB of RAM by this parameter:
```
-maxMem=4096
```

When running the CDLC and Mike Force, the CDLC starts at around 3.4GB of RAM. It rapidly increases to meet 4GB, at which point you'll notice some absolutely terrible performance issues.

If you increase this to `-maxMem=8191` and restart every 6 hours, you shouldn't have this problem!

Hope this helps!

**Comment by wildsevenmoony** [comment]
As much as I hoped this would have been the magic fix its not. I kinda knew yesterday already but I wanted an rpt without mods and higher maxMem (I actually forgot that I set my maxmem to 4GB)

So here is the new RPT without mods and 12GB of ram. The desync is still a massive issue. 

https://pastebin.com/uqDuKZjH

Also here is a screenshot of the #monitor command if it helps. I don't know most of the stuff it says but I know that in normal missions we have 49 FPS server side constantly and here we are between 15-30 FPS and sometimes it drops below 10 FPS.

![20210511202833_1](https://user-images.githubusercontent.com/24945079/117867104-37732c00-b298-11eb-9854-c487db8798ac.jpg)

I obviously know that this is a beta and stuff like this happens....just very sad that we for some reason have been hit by the issue.
