### ISSUE TITLE
Include MANPADS in OPFOR infantry spawn lists

### ISSUE THREAD

**Issue by darkcolouredbox** [Savage-Game-Design/Mike-Force#51]
**Is your feature request related to a problem? Please describe.**
Given the fun and exciting nature of flying CAS in Viet Nam, it's not uncommon to see 4-5 CAS assets at a time in any given AO. In the face of this overwhelming air superiority (and given how ineffective the randomly positioned AAA can be), the threat of large enemy forces is largely mitigated.

**Describe the solution you'd like**
Include OPFOR infantry carrying Igla or Strela tubes in the infantry spawn lists. This would increase the threat to BLUFOR air assets and limit the time they have to be on station.

**Describe alternatives you've considered**
Alternately, search for clear areas in which to spawn AAA emplacements, giving them a clearer view of the skies.

**Additional context**
N/A

**Comment by Doctor-Butts** [comment]
Maybe having the AAA emplacements spawn with clearer view, but a Strela is too powerful within the context of this scenario and ARMA: it would be more of an area denial and it would take forever for infantry/acav to root them out.

Strelas were most effective against rotary and propeller-driven fixed wing aircraft. They were not very effective against most jets, including the F-4. The reason is because the jets were fast enough. In the context of ARMA, jets are not going to be fast enough: they are vulnerable on take off/landing just about everywhere and the speeds they fly and the distances involved just don't make it fair.

As it is, small arms fire alone is deadly to helos with support or transport missions. The bigger AA would be more effective with a clearer view, but they are still really deadly.

Edit: 
If too much CAS is a concern, I think a better way going about it would be to limit the amount of CAS available at one time via params, playercount, or other.

**Comment by Spoffy** [comment]
We hear you loud and clear on the CAS issue - it's something that we're looking into! The Strela would be rather broken if given to infantry though - it's incredibly effective against every helicopter, and near impossible to provide sufficient counterplay to balance it out.
