### ISSUE TITLE
Microphone gets Disabled

### ISSUE THREAD

**Issue by rogerxx** [Savage-Game-Design/Mike-Force#55]
**Describe the bug**
Microphone is disabled upon joining, or eventually becomes disabled.

**To Reproduce**
Join a Mike Force enabled server, and try speaking into the microphone several times within an hour or two of game play.

**Expected behaviour**
Microphone should never become disabled, unless others choose to mute a player.  I sometimes randomly see this occur in the past, and seems to be usually caused by external modifications to the vanilla game.

**Screenshots**
Tough to take a screenshot of a playing laughing at your problem over his own working microphone.

**Environment (please complete the following information):**
Version: 
Map (specify if Altis Blufor):  Default Vietnam map
* [ X ] Official Server 
* [ ] Official InDev Server
* [ ] Private dedicated server
* [ ] Private dedicated server with Headless client(s)
* [ ] LAN Hosted

Additional mods: NONE on my client.
    
Time the bug occurred (Please leave in GMT+0): 2021.05.11 ~20:00 to 2021.05.11 ~00:30
If **Not** on an official server, please leave the time zone of your client for LAN, or the server for dedicated: 

**Additional context**
Personally, I've only seen an increase in glitches and bugs when people try to incorporate ill-maintained modifications or teamspeak.  Prefer official/vanilla builds when running applications on the Windows platform.

If you were LAN hosting, please attach your client .RPT file from when the bug occurred, If on a private dedicated server, please attach the server's .RPT from when the bug occurred.

**Comment by rogerxx** [comment]
[micrphone_gets_disabled-bug55-20210511.txt](https://github.com/Savage-Game-Design/Mike-Force/files/6463147/micrphone_gets_disabled-bug55-20210511.txt)

**Comment by rogerxx** [comment]
The attached RPT is from logging into another official Mike Force server, likely server no. 11.  The microphone problem might possibly be only on Mike Force official server no. 08?  

[arma3_x64_2021-05-11_20-05-44.zip](https://github.com/Savage-Game-Design/Mike-Force/files/6463151/arma3_x64_2021-05-11_20-05-44.zip)

**Comment by rogerxxxx** [comment]
I think the source of this bug is add-ons.

I would first check to see if any elements of Task Force Arrowhead Radio (TFAR) and/or Team Speak are integrated within the non-tfar/non-teamspeak servers.

I would next check if, first joining a Mike Force TFAR enabled server then subsequently quitting and joining a non-TFAR Mike Force server spawns this bug.

It is difficult for me to further make progress on this bug due to everybody being too quiet, at this time, on the Official SOG Mike Force servers.

**Comment by Spoffy** [comment]
This could be addon related, or could be because we have in-game VOIP disabled on TFAR-enabled servers. If you have a specific server this happens on, feel free to reply and re-open this ticket!

**Comment by rogerxxxx** [comment]
This bug was initially seen/experienced on the vanilla developer officially hosted non-TFAR servers.

Likely possibly something with the ranking system muting all non-rank users/players until increased rank was attained, or a script mistakenly assumed the non-TFAR server(s) were TFAR enabled servers and disabled in-game chat.  Regardless, I think this was solved/fixed awhile ago and I also use the very popular non-official Mike Force server now, as it disables ranking allowing using all features of the game per my work schedule at home.

I also last recently experienced some of the official non-TFAR servers were randomly disabling 3D view, so could have been something with an administrator logging in and playing with some setting/script, assuming the server was a TFAR server creating the anomaly.

**Comment by rogerxx** [comment]
Ran into this bug again on 2021.08.11 ~22:30-23:30 EDT on the public "Newby friendly" server.

I check microphone audio/recording ability prior to game start, using Audacity.

Something  I did immediately prior to loosing microphone audio while playing on the server, I was editing the Settings > key bindings.  As soon as other players mentioned my audio not being audible/heard, I checked back within the Windows audio/recording properties, and found the device recording levels not present while talking.  I then disabled/enabled the device and recording levels were once again present when talking.  I then entered the ARMA 3 settings and auto adjusted recording levels successfully, however microphone audio was still not present within the game server, without exiting and rejoining the server.

This sounds as if there is a bug within the map/scenario scripting.  Either somebody joins with TFAR plugin active and/or is using an incompatible plugin, and the map scenario scripting subsequently flips-out.
