### ISSUE TITLE
Arsenal Area Cleanup

### ISSUE THREAD

**Issue by ashton1cav** [Savage-Game-Design/Mike-Force#65]
**Is your feature request related to a problem? Please describe.**
It seems people still have the habbit of dropping junk around arsenals

**Describe the solution you'd like**
Some kind of junk cleanup for around arsenals when someone drops an item after a certain amount of time.

**Describe alternatives you've considered**
Currently performing server restarts every 6 hours to cleanup the junk.

**Additional context**

**Comment by freakierice** [comment]
I have also noticed this on our public file

Suggestion
Could run a basic trigger based script to delete dropped items in base when no players are present. With a large sleep on the checking in players are present.

**Comment by Dealman** [comment]
As a new MF player this is one of the first things I noticed, the ridiculous amount of clutter around arsenal boxes. Not sure how much this _actually_ impacts performance, but it's annoying nonetheless.

~~A more elegant solution might be to have a script attached to all arsenal boxes that run every N minutes, removes weapon holders _(weapons, ammo etc)_ within a certain distance.~~

**Edit:**

Here's a quick and a fairly straightforward method without having to change a bunch of systems;
```sqf
// To avoid assigning a variable name to the module, I fetched it like this. Probably wanna assign it a name instead
// this way, if more arsenals are to be added - they'll automatically be picked up so long as they're synched.
_arsenalModule = (entities "vn_module_whitelistedarsenal" select 0); 
_syncedArsenals = synchronizedObjects arsenalModule; 
_trash = [];
 
if(_syncedArsenals isEqualType []) then {
	{
		_items = nearestObjects [_x, ["WeaponHolderSimulated", "GroundWeaponHolder", "Default"], 100, true];
		if (count _items > 0) then {
			_trash append _items;
		}
	} forEach _syncedArsenals;
	
	if(count _trash > 0) then {
		{deleteVehicle _x} count _trash;
		_trash = [];
	}
}
```

Could probably also use `para_s_fnc_cleanup_add_items` to have it cleaned up using the already existing system if players aren't nearby. But since the arsenals are usually almost always occupied, chances are it'll never be cleaned up.

**Comment by Alablm** [comment]
Fixed in the current release, closing.
