### ISSUE TITLE
Can't walk while dragging in sprint mode

### ISSUE THREAD

**Issue by Kexanone** [Savage-Game-Design/Mike-Force#92]
**Describe the bug**
If you try to drag an unconscious player while in sprint mode, you can't walk at all. It's a common bug with the drag animation that plagues most medical systems. A possible solution is to set `forceWalk` to `true` during the dragging.

**To Reproduce**
1. Down someone
2. Get in sprint mode (_i.e._ 2xW)
3. Drag the person

**Expected behaviour**
You should be able to move

**Screenshots**
N/A

**Environment (please complete the following information):**
Version:  v0.65.03
Map (specify if Altis Blufor): Cam Lao Nam

* [x] Official Server
* [ ] Official InDev Server
* [ ] Private dedicated server
* [ ] Private dedicated server with Headless client(s)
* [ ] LAN Hosted

Additional mods:
None

**Additional context**
N/A

**Comment by aceb20** [comment]
We appreciate the feedback, however, this issue is a CDLC issue rather than an issue specifically with Mike Force. I'll kindly point you to the proper feedback tracker for Prairie Fire so our team can properly see the issue you reported!
https://community.sogpf.com/threads/44-Bug-reporting
Thanks again!

**Comment by Kexanone** [comment]
My bad, I wasn't aware that the revive system is part of the CDLC. Got captivated by Mike Force and didn't check out the actual CDLC missions yet.
